server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bancodados
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
