version: '3'
services:
  mysqlsamuel:
    image: mysql:latest
    ports:
      - 3307:3307
    restart: always
    environment:
      MYSQL_USER: dbmysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodados
    networks:
      - net
  spring-boot:
    image: imagem-spring-boot
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: spring-boot-api
    expose:
      - 8082:3307
  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - net

networks:
  net:
    driver: bridge