version: '3'
services:
  docker-mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: dbmysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodados
  
    networks:
      - net
  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8082
    networks:
      - net

networks:
  net:
    driver: bridge